### ISSUE TITLE
Amazon S3 Backend

### ISSUE THREAD

**Issue by glesage** [MrMaksimize/resutext#15]
Implement:
- Resume Upload
- Save URL to DB
- Resume Get
- Resume Update (**Overwrite uploaded one**? Versions?)

**Comment by MrMaksimize** [comment]
Hey Do you think this is like MVP functionality.  

The reason I ask is because this will be a bunch of extra work dealing with files and junk, and if people just wanna send their biz card, it's overkill.

**Comment by glesage** [comment]
so you think the MVP should not include resumes, just business cards... I mean I rmb w talked about this, but I still think we should include resumes in the MVP... and the best way is to ask for either a URL or put in on S3...

I think just an app that texts your linked-in and name to someone is not THAT usefull... you might as well just text it yourself...?

**Comment by glesage** [comment]
Actually screw this, I just read from an official Parse post that they use Amazon S3 for file storage anyway ha
