### ISSUE TITLE
Log in with LinkedIN

### ISSUE THREAD

**Issue by MrMaksimize** [MrMaksimize/resutext#16]
I think we can implement other ways to log in later, but initially i think people dont want to remember another damn user name / password.  If we can do it through linkedin i think that would be a big win

**Comment by glesage** [comment]
Alright, makes sense, but we gona have to do it the hard way.. no easy integration avail

**Comment by MrMaksimize** [comment]
Meh, it's oAuth so it's gonna be sexy :)

**Comment by MrMaksimize** [comment]
I'm mainly putting my thoughts down here in form of a comment.  

Originally I tried to do this with the linkedin JS API which is actually pretty sleek.  After the user authenticates you get a linkedin object usable in the front end that you can use to execute calls to linkedin.  

In retrospect, I could've used that object to initially populate the form, and we'd have the data anyway after the user has hit the save button on the form.  

However, thanks to @glesage's convincing me, -- jerk, I ended up going the backend integration route.  This is a bit more difficult since there are no SDKs available really for Parse or Node, and those that are available require the oauth library which carries along with it a bunch of dependencies.  

Anyway, that's where we are now.  I think I'm going to finish up writing the linked in integration on the backend, and see where it goes.  @glesage thoughts?

**Comment by glesage** [comment]
gud gud, keep at it :P
I will be back tmr and finishing up the resume saving in DB

**Comment by glesage** [comment]
@MrMaksimize get rid of userSettings
